#include <AFMotor.h>

int _ABVAR_1_sebb = 0 ;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  long duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  if ((duration < 2) || (duration > 300)) return false;
  return duration;
}

AF_DCMotor motor_dc_1(1, MOTOR12_64KHZ);
AF_DCMotor motor_dc_3(3, MOTOR34_64KHZ);

void setup()
{
  digitalWrite( A0 , LOW );

  Serial.begin(9600);
}

void loop()
{
  _ABVAR_1_sebb = 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( A0 , A1 ) ;
  Serial.print("message");
  Serial.print(" ");
  Serial.print(_ABVAR_1_sebb);
  Serial.print(" ");
  Serial.println();
  motor_dc_1.setSpeed(255);
  motor_dc_1.run(FORWARD);
  motor_dc_3.setSpeed(255);
  motor_dc_3.run(FORWARD);
  if (( ( _ABVAR_1_sebb ) <= ( 5 ) ))
  {
    Serial.print("turning");
    Serial.print(" ");
    Serial.println();
    motor_dc_1.setSpeed(255);
    motor_dc_1.run(FORWARD);
    motor_dc_3.setSpeed(255);
    motor_dc_3.run(BACKWARD);
    delay( 1000 );
  }
  else
  {
    Serial.print("moving");
    Serial.print(" ");
    Serial.println();
    motor_dc_1.setSpeed(255);
    motor_dc_1.run(FORWARD);
    motor_dc_3.setSpeed(255);
    motor_dc_3.run(FORWARD);
  }
}
